# Generated by Django 6.0.6 on 2026-07-06 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Singer",
            fields=[
                (
                    "mid",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="mid",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "intro",
                    models.TextField(blank=True, null=True, verbose_name="intro"),
                ),
                ("num_songs", models.IntegerField(null=True, verbose_name="num_songs")),
                (
                    "num_albums",
                    models.IntegerField(null=True, verbose_name="num_albums"),
                ),
                (
                    "num_movies",
                    models.IntegerField(null=True, verbose_name="num_movies"),
                ),
                (
                    "num_followers",
                    models.BigIntegerField(null=True, verbose_name="num_followers"),
                ),
            ],
            options={
                "verbose_name": "singer",
                "verbose_name_plural": "singers",
            },
        ),
        migrations.CreateModel(
            name="SingerSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GeMusic.singer",
                        verbose_name="singer",
                    ),
                ),
            ],
            options={
                "verbose_name": "singer_song_association",
                "verbose_name_plural": "singer_song_associations",
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "mid",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="mid",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "intro",
                    models.TextField(blank=True, null=True, verbose_name="intro"),
                ),
                (
                    "album",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="album"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="language"
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="style"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(null=True, verbose_name="release_date"),
                ),
                (
                    "lyrics",
                    models.TextField(blank=True, null=True, verbose_name="lyrics"),
                ),
                (
                    "num_comments",
                    models.IntegerField(null=True, verbose_name="num_comments"),
                ),
                (
                    "singers",
                    models.ManyToManyField(
                        related_name="songs",
                        through="GeMusic.SingerSong",
                        to="GeMusic.singer",
                    ),
                ),
            ],
            options={
                "verbose_name": "song",
                "verbose_name_plural": "songs",
            },
        ),
        migrations.AddField(
            model_name="singersong",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="GeMusic.song",
                verbose_name="song",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="comment_content")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="GeMusic.song",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="singersong",
            unique_together={("singer", "song")},
        ),
    ]
